version: '2'

services:

  webui:
    image: cvpz/webui
    build:
      context: ./src/WebUI
      dockerfile: Dockerfile
      
  identity.api:
    image: cvpz/identity.api
    build:
      context: ./src/Identity.api
      dockerfile: Dockerfile

  profile.api:
    image: cvpz/profile.api
    build:
      context: ./src/Profile.api
      dockerfile: Dockerfile

  projects.api:
    image: cvpz/projects.api
    build:
      context: ./src/Projects.api
      dockerfile: Dockerfile